# Generated by Django 4.2.7 on 2023-12-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappsitio', '0004_historial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medida', models.CharField(choices=[('gr', 'Gramos'), ('ml', 'Mililitros')], max_length=10)),
            ],
        ),
    ]
