# Generated by Django 4.2.7 on 2023-12-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappsitio', '0005_alimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
