# Generated by Django 4.2.7 on 2023-12-03 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappsitio', '0007_rename_numero_compra_historial_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='nombre',
        ),
    ]
