# Generated by Django 4.2.7 on 2023-12-03 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappsitio', '0008_remove_historial_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='precio_total',
        ),
    ]
