# Generated by Django 4.2.7 on 2023-12-03 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappsitio', '0009_remove_historial_precio_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='historial',
        ),
        migrations.AlterField(
            model_name='historial',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_compras', to=settings.AUTH_USER_MODEL),
        ),
    ]
