# Generated by Django 4.2.7 on 2023-12-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myappsitio', '0010_remove_usuario_historial_alter_historial_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_compras', to='myappsitio.usuario'),
        ),
    ]
