# Generated by Django 4.2.7 on 2023-12-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappsitio', '0011_alter_historial_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='usuario',
        ),
    ]
