# Generated by Django 4.2.7 on 2023-12-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myappsitio', '0012_remove_historial_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historial',
            old_name='orden',
            new_name='detalles',
        ),
    ]
